eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
      instance-id: service-order-8010 #自定义服务名称
      prefer-ip-address: true #访问路径显示ip地址
server:
  port: 8010
spring:
  application:
    name: service-order